[
  {
    "timestamp": "2025-05-09T12:41:32.997478",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 19.63374614715576,
        "throughput_samples_per_sec": 50.932715158124054
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T12:42:34.808288",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 20.467662811279297,
        "throughput_samples_per_sec": 48.85755687986618
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T12:42:38.774140",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 21.21434211730957,
        "throughput_samples_per_sec": 47.13792181111583
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T12:58:57.165325",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 19.108986854553223,
        "throughput_samples_per_sec": 52.33139818512793
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  }
]