[
  {
    "timestamp": "2025-05-03T22:37:52.537570",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 17.96550750732422,
        "throughput_samples_per_sec": 55.66221825864467
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:38:44.189350",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.37594509124756,
        "throughput_samples_per_sec": 54.41896974737364
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:38:46.940619",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 17.984890937805176,
        "throughput_samples_per_sec": 55.60222763975443
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:39:38.468081",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.086647987365723,
        "throughput_samples_per_sec": 55.28940468673586
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:39:41.200488",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.036508560180664,
        "throughput_samples_per_sec": 55.443102896738424
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:40:32.706646",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.094968795776367,
        "throughput_samples_per_sec": 55.263980352008936
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:40:35.440661",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 17.89088249206543,
        "throughput_samples_per_sec": 55.89439204262271
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:41:27.030512",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.555808067321777,
        "throughput_samples_per_sec": 53.89148219101694
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:41:29.775201",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.21112632751465,
        "throughput_samples_per_sec": 54.91148553997617
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:42:21.392777",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.44046115875244,
        "throughput_samples_per_sec": 54.22857874274839
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:42:24.130895",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.082165718078613,
        "throughput_samples_per_sec": 55.303110014095076
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-03T22:43:15.550854",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 18.26939582824707,
        "throughput_samples_per_sec": 54.73634757280033
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 579, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  }
]