[
  {
    "timestamp": "2025-05-09T15:17:15.853989",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.796929359436035,
        "throughput_samples_per_sec": 102.07279886496654
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:17:48.688753",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.393906593322754,
        "throughput_samples_per_sec": 106.45198459933657
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:17:51.309309",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.56270694732666,
        "throughput_samples_per_sec": 104.57290027899045
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:18:25.210758",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.305453300476074,
        "throughput_samples_per_sec": 107.46386744521507
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:18:27.786944",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.37337875366211,
        "throughput_samples_per_sec": 106.68511603772625
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:19:00.056367",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.18736457824707,
        "throughput_samples_per_sec": 108.84514176869618
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:19:02.630053",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.203529357910156,
        "throughput_samples_per_sec": 108.65396970136572
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:19:34.767720",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 10.411977767944336,
        "throughput_samples_per_sec": 96.04323235098806
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:19:37.365789",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.203481674194336,
        "throughput_samples_per_sec": 108.65453264321722
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:20:09.624954",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.48495864868164,
        "throughput_samples_per_sec": 105.43008536352393
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:20:12.193686",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.351730346679688,
        "throughput_samples_per_sec": 106.9320823985315
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:20:44.460740",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.453320503234863,
        "throughput_samples_per_sec": 105.78293623471315
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:20:47.038916",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.269165992736816,
        "throughput_samples_per_sec": 107.88457136096014
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:21:19.071540",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.295129776000977,
        "throughput_samples_per_sec": 107.58322090154053
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:21:21.645490",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.467577934265137,
        "throughput_samples_per_sec": 105.62363541585347
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:21:53.732929",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.308147430419922,
        "throughput_samples_per_sec": 107.4327633371925
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:21:56.305907",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.534478187561035,
        "throughput_samples_per_sec": 104.88250959602905
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  },
  {
    "timestamp": "2025-05-09T15:22:28.578689",
    "metrics": {
      "inference": {
        "batch_size": 1,
        "num_runs": 10,
        "avg_latency_ms": 9.32154655456543,
        "throughput_samples_per_sec": 107.27833564380241
      },
      "training_step": {
        "error": "in user code:\n\n    File \"/home/p0wden/Downloads/mloptimizer/app/common/GpuMetrics.py\", line 588, in train_step  *\n        loss = model.loss(y, y_pred)\n\n    TypeError: 'str' object is not callable\n"
      },
      "data_pipeline": {
        "status": "no dataset provided"
      }
    }
  }
]